name: Nailing application

on: [push]
# pull_request:
#  branches: [develop]

jobs:
  build_backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nailing
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: "11"
        distribution: "temurin"
    - name: Build with Maven
      run: |
          mvn --batch-mode --update-snapshots verify
          
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/web-app
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install frontend dependencies
        run: npm install
    
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
  #     with:
  #         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #         heroku_app_name: " <<your app name>>"
  #         heroku_email: " <<your email>>"
